"""
LabInsight – Groq AI analysis service.

Sends extracted lab data to a Groq-hosted LLM and parses the structured
JSON response into a validated ``AnalysisResult``. The system prompt is
carefully engineered to produce consistent, non-alarming medical analysis.
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

from dotenv import load_dotenv
from groq import Groq

from models.schemas import (
    AnalysisResult,
    DISCLAIMER_TEXT,
    OverallStatus,
    RiskAssessment,
    RiskLevel,
)

logger = logging.getLogger(__name__)

# Load .env from the backend directory (supports both dev & production)
load_dotenv()

# ---------------------------------------------------------------------------
# Prompt engineering
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a highly experienced clinical laboratory report analyst AI. Your role
is to interpret lab results and produce a clear, structured analysis that
helps patients understand their health. Follow these guidelines strictly:

1. **Accuracy** – Base your analysis ONLY on the lab values and text provided.
   Do NOT fabricate values or invent test names that are not present.

2. **Tone** – Be thorough yet reassuring. Explain abnormalities in plain
   language without being alarming. Use phrases like "slightly above the
   typical range" instead of "dangerously high" unless truly critical.

3. **JSON output** – Respond with ONLY a valid JSON object (no markdown fences,
   no commentary before or after). The JSON must match this schema exactly:

{
  "patient_info": {
    "name": "<string or null>",
    "lab_name": "<string or null>",
    "report_date": "<string or null>"
  },
  "overall_summary": "<A 2-4 sentence executive summary of the report.>",
  "overall_status": "<One of: Healthy | Mild Concern | Needs Attention | Critical Review Recommended>",
  "lab_values": [
    {
      "test_name": "<string>",
      "measured_value": "<string>",
      "unit": "<string>",
      "reference_range": "<string>",
      "status": "<normal|low|high|critical>"
    }
  ],
  "abnormal_markers": [
    {
      "test_name": "<string>",
      "value": "<string>",
      "unit": "<string>",
      "reference_range": "<string>",
      "status": "<low|high|critical>",
      "explanation": "<plain-language explanation>",
      "severity": "<mild|moderate|severe|critical>",
      "potential_causes": ["<cause 1>", "<cause 2>"]
    }
  ],
  "risk_assessment": {
    "score": <0-100>,
    "level": "<Low|Moderate|High|Critical>",
    "description": "<How the score was determined>"
  },
  "health_concerns": [
    {
      "area": "<e.g. Liver Function>",
      "description": "<Why this is a concern>",
      "related_markers": ["<test name>"]
    }
  ],
  "recommendations": [
    {
      "category": "<lifestyle|diet|exercise|follow_up|consultation>",
      "text": "<actionable recommendation>",
      "priority": <1-5>
    }
  ],
  "disclaimer": "This analysis is generated by an AI system and is intended for informational purposes only. It does NOT constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for interpretation of your lab results and any health-related decisions."
}

4. **Completeness** – Include ALL lab values from the input in the lab_values
   array (even normal ones). Only include truly abnormal markers in
   abnormal_markers.

5. **Recommendations** – Provide at least one recommendation. Always include
   a "follow_up" or "consultation" recommendation if any marker is abnormal.

6. **Risk score** – 0-15 = Low, 16-40 = Moderate, 41-70 = High, 71-100 = Critical.
   Base the score on the count and severity of abnormal markers.

7. **Comprehensive Insights** – In the `health_concerns` array, you MUST systematically cover every single abnormal marker. Group related abnormal markers into clinical areas (e.g., "Liver Function", "Lipid Panel", "Electrolyte Balance"). You must be exhaustive and consistent—never omit a clinical area that has abnormal values. If all markers are normal, provide a general "Overall Health" insight.
"""

USER_PROMPT_TEMPLATE = """\
Analyze the following laboratory report data and return a JSON analysis.

## Structured Lab Values (regex-extracted)
{structured_values}

## Patient Info (regex-extracted)
{patient_info}

## Full Report Text (for additional context)
{raw_text}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_user_prompt(extracted_data: dict[str, Any]) -> str:
    structured = json.dumps(extracted_data.get("lab_values", []), indent=2)
    patient = json.dumps(extracted_data.get("patient_info", {}), indent=2)
    raw = extracted_data.get("raw_text", "")
    # Truncate raw text to avoid hitting token limits
    if len(raw) > 6000:
        raw = raw[:6000] + "\n... [truncated]"
    return USER_PROMPT_TEMPLATE.format(
        structured_values=structured,
        patient_info=patient,
        raw_text=raw,
    )


def _extract_json_from_response(text: str) -> dict:
    """Try to extract a JSON object from the LLM response, even if it
    contains surrounding markdown fences or commentary."""
    # Try direct parse first
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Strip markdown code fences
    cleaned = re.sub(r"^```(?:json)?\s*", "", text, flags=re.MULTILINE)
    cleaned = re.sub(r"```\s*$", "", cleaned, flags=re.MULTILINE).strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass

    # Try to find the first { ... } block
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    raise ValueError("Could not extract valid JSON from Groq response")


def _fallback_analysis(extracted_data: dict[str, Any], error_msg: str) -> AnalysisResult:
    """Return a minimal but valid AnalysisResult when the AI response
    cannot be parsed."""
    from models.schemas import LabValue, PatientInfo

    patient_raw = extracted_data.get("patient_info", {})
    lab_values_raw = extracted_data.get("lab_values", [])

    lab_values = [LabValue(**lv) for lv in lab_values_raw]
    patient_info = PatientInfo(**patient_raw)

    abnormal_count = sum(1 for lv in lab_values if lv.status != "normal")

    return AnalysisResult(
        patient_info=patient_info,
        overall_summary=(
            f"We were unable to fully process the AI analysis ({error_msg}). "
            f"However, we extracted {len(lab_values)} lab values from your report, "
            f"of which {abnormal_count} appear outside the normal range. "
            "Please consult a healthcare professional for a complete interpretation."
        ),
        overall_status=OverallStatus.NEEDS_ATTENTION if abnormal_count > 0 else OverallStatus.HEALTHY,
        lab_values=lab_values,
        abnormal_markers=[],
        risk_assessment=RiskAssessment(
            score=0,
            level=RiskLevel.LOW,
            description="Automated risk scoring was unavailable.",
        ),
        health_concerns=[],
        recommendations=[],
        disclaimer=DISCLAIMER_TEXT,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def analyze_report(extracted_data: dict[str, Any]) -> AnalysisResult:
    """Send extracted lab data to Groq and return a validated AnalysisResult.

    Parameters
    ----------
    extracted_data:
        The dict returned by ``lab_extractor.extract_lab_values()``.

    Returns
    -------
    AnalysisResult
        Fully validated Pydantic model.

    Raises
    ------
    RuntimeError
        If the GROQ_API_KEY environment variable is not set.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is not set. Please add it to your .env file."
        )

    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

    client = Groq(api_key=api_key)
    user_prompt = _build_user_prompt(extracted_data)

    logger.info("Sending analysis request to Groq model=%s", model)

    try:
        chat_completion = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.0,
            seed=42,
            max_tokens=4096,
        )

        response_text = chat_completion.choices[0].message.content
        logger.debug("Groq raw response length: %d chars", len(response_text or ""))

        if not response_text:
            return _fallback_analysis(extracted_data, "Empty response from Groq")

        data = _extract_json_from_response(response_text)

        # Validate through Pydantic
        result = AnalysisResult.model_validate(data)

        # Always enforce our disclaimer
        result.disclaimer = DISCLAIMER_TEXT

        return result

    except ValueError as exc:
        logger.error("JSON parsing failed: %s", exc)
        return _fallback_analysis(extracted_data, str(exc))
    except Exception as exc:
        logger.error("Groq API call failed: %s", exc)
        return _fallback_analysis(extracted_data, str(exc))
