"""
LabInsight – Pydantic data models for the analysis pipeline.

Every model uses strict validation so that invalid payloads are caught early
and clear error messages are returned to the frontend.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class ValueStatus(str, Enum):
    """Status of an individual lab measurement relative to the reference range."""
    NORMAL = "normal"
    LOW = "low"
    HIGH = "high"
    CRITICAL = "critical"


class OverallStatus(str, Enum):
    """High-level health status derived from the full report."""
    HEALTHY = "Healthy"
    MILD_CONCERN = "Mild Concern"
    NEEDS_ATTENTION = "Needs Attention"
    CRITICAL_REVIEW = "Critical Review Recommended"


class RecommendationCategory(str, Enum):
    """Category bucket for actionable recommendations."""
    LIFESTYLE = "lifestyle"
    DIET = "diet"
    EXERCISE = "exercise"
    FOLLOW_UP = "follow_up"
    CONSULTATION = "consultation"


class RiskLevel(str, Enum):
    """Qualitative risk level."""
    LOW = "Low"
    MODERATE = "Moderate"
    HIGH = "High"
    CRITICAL = "Critical"


class Severity(str, Enum):
    """Severity of an abnormal marker."""
    MILD = "mild"
    MODERATE = "moderate"
    SEVERE = "severe"
    CRITICAL = "critical"


# ---------------------------------------------------------------------------
# Core value models
# ---------------------------------------------------------------------------

class LabValue(BaseModel):
    """A single laboratory test measurement."""
    test_name: str = Field(..., description="Name of the laboratory test")
    measured_value: str = Field(..., description="Measured value (kept as string to support ranges & qualitative results)")
    unit: str = Field("", description="Unit of measurement (e.g. mg/dL)")
    reference_range: str = Field("", description="Normal reference range (e.g. '3.5-5.5')")
    status: ValueStatus = Field(ValueStatus.NORMAL, description="Interpretation relative to reference range")


class PatientInfo(BaseModel):
    """Optional patient / report metadata extracted from the PDF."""
    name: Optional[str] = Field(None, description="Patient name, if found")
    lab_name: Optional[str] = Field(None, description="Name of the laboratory")
    report_date: Optional[str] = Field(None, description="Date the report was generated")


# ---------------------------------------------------------------------------
# Analysis detail models
# ---------------------------------------------------------------------------

class AbnormalMarker(BaseModel):
    """Detailed breakdown of a single abnormal lab result."""
    test_name: str
    value: str
    unit: str = ""
    reference_range: str = ""
    status: ValueStatus
    explanation: str = Field("", description="Plain-language explanation of what this marker means")
    severity: Severity = Field(Severity.MILD, description="How far out of range / how clinically significant")
    potential_causes: List[str] = Field(default_factory=list, description="Possible reasons for the abnormality")


class RiskAssessment(BaseModel):
    """Aggregate risk score for the entire report."""
    score: int = Field(0, ge=0, le=100, description="Numerical risk score (0 = no risk, 100 = maximum)")
    level: RiskLevel = Field(RiskLevel.LOW, description="Qualitative risk level")
    description: str = Field("", description="Summary of how the score was determined")


class HealthConcern(BaseModel):
    """A health area flagged by the analysis."""
    area: str = Field(..., description="Health area (e.g. 'Liver Function')")
    description: str = Field("", description="Why this area is of concern")
    related_markers: List[str] = Field(default_factory=list, description="Lab tests related to this concern")


class Recommendation(BaseModel):
    """An actionable recommendation for the patient."""
    category: RecommendationCategory = Field(..., description="Recommendation category")
    text: str = Field(..., description="The recommendation itself")
    priority: int = Field(1, ge=1, le=5, description="Priority (1 = highest, 5 = lowest)")


# ---------------------------------------------------------------------------
# Top-level analysis result
# ---------------------------------------------------------------------------

DISCLAIMER_TEXT = (
    "This analysis is generated by an AI system and is intended for informational "
    "purposes only. It does NOT constitute medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare professional for interpretation of your "
    "lab results and any health-related decisions."
)


class AnalysisResult(BaseModel):
    """Complete analysis output returned by the /api/upload-and-analyze endpoint."""
    patient_info: PatientInfo = Field(default_factory=PatientInfo)
    overall_summary: str = Field("", description="Executive summary of the report findings")
    overall_status: OverallStatus = Field(OverallStatus.HEALTHY, description="High-level status")
    lab_values: List[LabValue] = Field(default_factory=list, description="All extracted lab measurements")
    abnormal_markers: List[AbnormalMarker] = Field(default_factory=list, description="Details on abnormal results")
    risk_assessment: RiskAssessment = Field(default_factory=RiskAssessment)
    health_concerns: List[HealthConcern] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)
    disclaimer: str = Field(default=DISCLAIMER_TEXT)
